const getQuery = (args, queryName) => {
    console.log('--DEBUG-- updateStair ARGS!: ',  args);

    const queries = {
        'createComplete': `
            INSERT INTO stairs_server.dbo.Complete (
                WOID,
                WONUM,
                REID,
                ceid,
                aeid,
                Delivery,
                StairType,
                CutBase,
                CutBlock,
                CutRises,
                CutStringers,
                CutTread,
                RDate,
                CDate,
                ADate,
                CutBaseDate,
                CutBlockDate,
                CutRisesDate,
                CutStringersDate,
                CutTreadDate,
                Location,
                ShipFlag,
                ShipDate
            ) VALUES (
                ${args.id},
                ${args.orderNum},
                0,
                0,
                0,
                ${args.deliveryDate},
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                '${args.location}',
                1,
                0
        )`,

        'createUncomplete': `
            INSERT INTO stairs_server.dbo.Uncomplete (
                WOID,
                WONUM,
                Delivery,
                RComplete,
                reID,
                CComplete,
                ceID,
                AComplete,
                aeID,
                StairType,
                CutBase,
                CutBlock,
                CutRises,
                CutStringers,
                CutTread,
                RDate,
                CDate,
                ADate,
                CutBaseDate,
                CutBlockDate,
                CutRisesDate,
                CutStringersDate,
                CutTreadDate,
                Location,
                ShipFlag,
                ShipDate
            ) VALUES (
                ${args.id},
                ${args.orderNum},
                ${args.deliveryDate},
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                '${args.location}',
                0,
                0
        )`,

        'createOrdersExtension': `
            INSERT INTO stairs.dbo.WorkOrderExtensions (
                WONum,
                WOID,
                PublicComment,
                OffTheTop,
                WinderSeatLength,
                RunAccuracy,
                MeasureTrips,
                InstallTrips,
                DistanceToSite,
                InvoiceNo,
                SalesPerson,
                StringerOnly,
                NumStringers,
                TempStairsInc,
                TempStairsCharge,
                CustomDelivery,
                DeliveryComments
            ) VALUES (
                ${args.orderNum},
                ${args.id},
                '',
                0,
                0,
                4,
                0,
                0,
                0,
                '',
                '',
                0,
                0,
                0,
                '',
                '',
                NULL
        )`,

        'createOrder': `INSERT INTO stairs.dbo.Workorders (
            ID,
            OrderNum, 
            Customer, 
            BillingAddress, 
            Address, 
            Model, 
            PONum, 
            JobNum, 
            StairsNum, 
            OrderDate, 
            DeliveryDate, 
            Location, 
            Height, 
            Width, 
            Length, 
            HeadroomMatters, 
            Opening, 
            Joist, 
            Style, 
            StairType, 
            RiserType, 
            Sill,
            Method, 
            OneInchPly,
            HalfInchPly, 
            meas2X6, 
            meas2x10, 
            meas2x12, 
            Status, 
            NumRisers, 
            OSM,
            Type,
            CTR,
            TypeR, 
            ThreeEightTop, 
            Notch, 
            TotalHeight, 
            NumStrcasesInHeight, 
            Materials, 
            StringerStyle1, 
            StringerStyle2, 
            Divisor, 
            CutlistComments, 
            WorkorderComments,
            BillingComments,
            InvoiceComments,
            CustomNumCustomTreads,
            CustomWindersType,
            CustomWindersL,
            CustomWindersR,
            CustomWindersSameWP,
            CustomBullnoseType,
            CustomBullnoseL,
            CustomBullnoseR,
            CustomFlairsType,
            CustomFlairsL,
            CustomFlairsR,
            CustomLandingL,
            WindersAndLandings,
            WorkorderCommentsOverride,
            WinderLocation,
            WinderDirection,
            WinderRise,
            WinderPickup,
            WinderWrap,
            WinderOn1,
            WinderOn3,
            WinderSeat,
            WinderCutCorner,
            Landing_PU,
            Landing_Seat,
            Landing_PU_OSM,
            Landing_Wrap,
            Landing_Wrap_OSM,
            Landing_On_Floor,
            CustomFlairsTypeRight,
            CustomBullnoseTypeRight,
            CustDesc,
            blurb_winder,
            blurb_left_bullnose,
            blurb_right_bullnose,
            blurb_left_flair,
            blurb_right_flair,
            blurb_landing,
            CustomPic,
            Connected,
            ConnectedTo,
            Furred,
            SquareLanding,
            InputBy,
            Quote,
            Edit,
            NoNosing
        )
        VALUES (
            ${args.id},
            ${args.orderNum},
            ${args.customer},
            '${args.billingAddress}',
            '${args.deliveryAddress}',
            ${args.model},
            ${args.po},
            '${args.jobNum}',
            ${args.numOfStairs},
            ${args.orderDate},
            ${args.deliveryDate},
            '',
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            'B',
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            'plywood tread, spruce stringers',
            -1,
            -1,
            0,
            '',
            '',
            '',
            '',
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            '',
            '',
            0,
            0,
            0,
            0,
            0,
            0,
            '',
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            0,
            0,
            '',
            0,
            0,
            '${args.input}',
            ${args.quote ? 1 : 0},
            0,
            0
        )`,

        'updateStairOrder': `UPDATE 
                            Workorders
                        SET Location='${args.location}',
                            NumRisers=${args.numberOfRises},
                            Style=${args.stairStyle},
                            StairType=${args.stairType},
                            RiserType=${args.riserType},
                            Length=${args.lngth},
                            Height=${args.height},
                            Width=${args.width},
                            Method='${args.method}',
                            Notch=${args.notch},
                            OSM=${args.osm},
                            HeadroomMatters=${args.headroomMatters},
                            NoNosing=${args.noNosing},
                            Furred=${args.thirdAndFurred},
                            Materials='${args.materials}',
                            StringerStyle1=${args.stringerStyle1},
                            StringerStyle2=${args.stringerStyle2},
                            Divisor=${args.divisor},
                            Connected=${args.connectedToOthers},
                            TotalHeight=${args.totalHeight},
                            NumStrcasesInHeight=${args.numStrcasesInHeight},
                            WindersAndLandings=${args.numberWindersAndLanding},
                            CustomNumCustomTreads=${args.numberOfTreads},
                            ConnectedTo='${args.connectedTo}',
                            CutlistComments='${args.cutlistComments}',
                            WorkorderComments='${args.workorderComments}',
                            BillingComments='${args.billingComments}',
                            InvoiceComments='${args.invoiceComments}',
                            OneInchPly=${args.oneInchPly},
                            HalfInchPly=${args.halfInchPly},
                            meas2X6=${args.meas2X6},
                            meas2X10=${args.meas2x10},
                            meas2X12=${args.meas2x12},
                            Joist=${args.joist},
                            Sill=${args.sill},
                            Opening=${args.opening},
                            third=${args.third},
                            blurb_left_flair='${args.blurbLeftFlair}',
                            blurb_right_flair='${args.blurbRightFlair}',
                            blurb_left_bullnose='${args.blurbLeftBullnose}',
                            blurb_right_bullnose='${args.blurbRightBullnose}',
                            CustomFlairsType='${args.customFlairsType}',
                            CustomFlairsTypeRight='${args.customFlairsTypeRight}',
                            CustomBullnoseType='${args.customBullnoseType}',
                            CustomBullnoseTypeRight='${args.customBullnoseTypeRight}'
                        WHERE ID=${args.id}`,
        'updateWinderOrder': `UPDATE 
                            Workorders
                        SET Location='${args.location}',
                            NumRisers=${args.numberOfRises},
                            Style=${args.stairStyle},
                            RiserType=${args.riserType},
                            
                            Connected=${args.connectedToOthers},
                            TotalHeight=${args.totalHeight},
                            NumStrcasesInHeight=${args.numStrcasesInHeight},
                            WindersAndLandings=${args.numberWindersAndLanding},
                            ConnectedTo='${args.connectedTo}',

                            CutlistComments='${args.cutlistComments}',
                            WorkorderComments='${args.workorderComments}',
                            BillingComments='${args.billingComments}',
                            InvoiceComments='${args.invoiceComments}',

                            WinderRise=${args.winderRise},
                            WinderWrap=${args.winderWrap},
                            WinderPickup=${args.winderPickup},
                            WinderOn1=${args.winderOn1},
                            WinderOn3=${args.winderOn3},
                            WinderSeat=${args.winderSeat},
                            WinderLocation='${args.location}',
                            WinderCutCorner='${args.winderCutCorner}',
                            CustomWindersType=${args.customWindersType},
                            CustomWindersL=${args.customWindersL},
                            CustomWindersR=${args.customWindersR},
                            blurb_winder='${args.blurbWinder}'
                        WHERE ID=${args.id}`,
        'updateLandingOrder': `UPDATE 
                    Workorders
                SET Location='${args.location}',
                    
                    Connected=${args.connectedToOthers},
                    TotalHeight=${args.totalHeight},
                    NumStrcasesInHeight=${args.numStrcasesInHeight},
                    WindersAndLandings=${args.numberWindersAndLanding},
                    ConnectedTo='${args.connectedTo}',
                    StringerStyle1='${args.stringerStyle1}',

                    CutlistComments='${args.cutlistComments}',
                    WorkorderComments='${args.workorderComments}',
                    BillingComments='${args.billingComments}',
                    InvoiceComments='${args.invoiceComments}',

                    Landing_PU='${args.landingPickup}',
                    Landing_Wrap='${args.landingWrapPlusOneNosing}',
                    Landing_Seat='${args.landingSeat}',
                    Landing_PU_OSM=${args.landingOsmOnPickup},
                    Landing_Wrap_OSM=${args.landingOsmOnWrap},
                    Landing_On_Floor=${args.landingSitsOnFloor},
                    CustomLandingL=${args.customLandingL},
                    SquareLanding=${args.squareLanding},
                    blurb_landing='${args.blurbLanding}'
                WHERE ID=${args.id}`,
        
        'createFullWorkorder': `INSERT INTO stairs.dbo.${args.TableName} (
            ID,
            OrderNum, 
            Customer, 
            BillingAddress, 
            Address, 
            Model, 
            PONum, 
            JobNum, 
            StairsNum, 
            OrderDate, 
            DeliveryDate, 
            Location, 
            Height, 
            Width, 
            Length, 
            HeadroomMatters, 
            Opening, 
            Joist, 
            Style, 
            StairType, 
            RiserType, 
            Sill,
            Method, 
            OneInchPly,
            HalfInchPly, 
            meas2X6, 
            meas2x10, 
            meas2x12, 
            Status, 
            NumRisers, 
            OSM,
            Type,
            CTR,
            TypeR, 
            ThreeEightTop, 
            Notch, 
            TotalHeight, 
            NumStrcasesInHeight, 
            Materials, 
            StringerStyle1, 
            StringerStyle2, 
            Divisor, 
            CutlistComments, 
            WorkorderComments,
            BillingComments,
            InvoiceComments,
            CustomNumCustomTreads,
            CustomWindersType,
            CustomWindersL,
            CustomWindersR,
            CustomWindersSameWP,
            CustomBullnoseType,
            CustomBullnoseL,
            CustomBullnoseR,
            CustomFlairsType,
            CustomFlairsL,
            CustomFlairsR,
            CustomLandingL,
            WindersAndLandings,
            WorkorderCommentsOverride,
            WinderLocation,
            WinderDirection,
            WinderRise,
            WinderPickup,
            WinderWrap,
            WinderOn1,
            WinderOn3,
            WinderSeat,
            WinderCutCorner,
            Landing_PU,
            Landing_Seat,
            Landing_PU_OSM,
            Landing_Wrap,
            Landing_Wrap_OSM,
            Landing_On_Floor,
            CustomFlairsTypeRight,
            CustomBullnoseTypeRight,
            CustDesc,
            blurb_winder,
            blurb_left_bullnose,
            blurb_right_bullnose,
            blurb_left_flair,
            blurb_right_flair,
            blurb_landing,
            CustomPic,
            Connected,
            ConnectedTo,
            Furred,
            SquareLanding,
            InputBy,
            Quote,
            ${args.TableName !== 'Quotes' ? 'Edit,' : ''}
            NoNosing
        )
        VALUES (
            ${args.NewID},
            ${args.NewOrderNum},
            ${args.Customer},
            '${args.BillingAddress}',
            '${args.Address}',
            ${args.Model || 0},
            '${args.PONum}',
            '${args.JobNum}',
            ${args.StairsNum},
            ${args.OrderDate},
            ${args.DeliveryDate},
            '${args.Location}',
            ${args.Height},
            ${args.Width},
            ${args.Length},
            ${args.HeadroomMatters ? 1 : 0},
            ${args.Opening},
            ${args.Joist},
            ${args.Style},
            ${args.StairType},
            ${args.RiserType},
            ${args.Sill},
            '${args.Method}',
            ${args.OneInchPly},
            ${args.HalfInchPly},
            ${args.meas2X6},
            ${args.meas2x10},
            ${args.meas2x12},
            ${args.Status},
            ${args.NumRisers},
            ${args.OSM},
            '${args.Type}',
            ${args.CTR},
            ${args.TypeR},
            ${args.ThreeEightTop ? 1 : 0},
            ${args.Notch ? 1 : 0},
            ${args.TotalHeight},
            ${args.NumStrcasesInHeight},
            '${args.Materials}',
            ${args.StringerStyle1},
            ${args.StringerStyle2},
            ${args.Divisor},
            '${args.CutlistComments}',
            '${args.WorkorderComments}',
            '${args.BillingComments}',
            '${args.InvoiceComments}',
            ${args.CustomNumCustomTreads},
            ${args.CustomWindersType},
            ${args.CustomWindersL ? 1 : 0},
            ${args.CustomWindersR ? 1 : 0},
            ${args.CustomWindersSameWP ? 1 : 0},
            ${args.CustomBullnoseType},
            ${args.CustomBullnoseL ? 1 : 0},
            ${args.CustomBullnoseR ? 1 : 0},
            ${args.CustomFlairsType},
            ${args.CustomFlairsL ? 1 : 0},
            ${args.CustomFlairsR ? 1 : 0},
            ${args.CustomLandingL ? 1 : 0},
            ${args.WindersAndLandings},
            ${args.WorkorderCommentsOverride ? 1 : 0},
            '${args.WinderLocation}',
            '${args.WinderDirection}',
            ${args.WinderRise},
            ${args.WinderPickup},
            ${args.WinderWrap},
            ${args.WinderOn1},
            ${args.WinderOn3},
            ${args.WinderSeat ? 1 : 0},
            '${args.WinderCutCorner}',
            ${args.Landing_PU},
            ${args.Landing_Seat},
            ${args.Landing_PU_OSM},
            ${args.Landing_Wrap},
            ${args.Landing_Wrap_OSM},
            ${args.Landing_On_Floor ? 1 : 0},
            ${args.CustomFlairsTypeRight},
            ${args.CustomBullnoseTypeRight},
            '${args.CustDesc}',
            '${args.blurb_winder}',
            '${args.blurb_left_bullnose}',
            '${args.blurb_right_bullnose}',
            '${args.blurb_left_flair}',
            '${args.blurb_right_flair}',
            '${args.blurb_landing}',
            ${args.CustomPic ? 1 : 0},
            ${args.Connected ? 1 : 0},
            '${args.ConnectedTo}',
            ${args.Furred ? 1 : 0},
            ${args.SquareLanding ? 1 : 0},
            '${args.InputBy}',
            ${args.Quote ? 1 : 0},
            ${args.TableName !== 'Quotes' ? (args.Edit ? (1 + ',') : (0 + ',')) : ''}
            ${args.NoNosing ? 1 : 0}
        )`,

        'createFullWorkorderExtension': `
            INSERT INTO stairs.dbo.WorkOrderExtensions (
                WONum,
                WOID,
                PublicComment,
                OffTheTop,
                WinderSeatLength,
                RunAccuracy,
                MeasureTrips,
                InstallTrips,
                DistanceToSite,
                InvoiceNo,
                SalesPerson,
                StringerOnly,
                NumStringers,
                TempStairsInc,
                TempStairsCharge,
                CustomDelivery,
                DeliveryComments
            ) VALUES (
                ${args.NewOrderNum},
                ${args.NewID},
                '${args.PublicComment}',
                ${args.OffTheTop},
                ${args.WinderSeatLength},
                ${args.RunAccuracy},
                ${args.MeasureTrips},
                ${args.InstallTrips},
                ${args.DistanceToSite},
                '${args.InvoiceNo}',
                '${args.SalesPerson}',
                ${args.StringerOnly ? 1 : 0},
                ${args.NumStringers},
                ${args.TempStairsInc ? 1 : 0},
                '${args.TempStairsCharge}',
                '${args.CustomDelivery}',
                '${args.DeliveryComments}'
        )`,

        'createFullComplete': `
            INSERT INTO stairs_server.dbo.Complete (
                WOID,
                WONUM,
                REID,
                ceid,
                aeid,
                Delivery,
                StairType,
                CutBase,
                CutBlock,
                CutRises,
                CutStringers,
                CutTread,
                RDate,
                CDate,
                ADate,
                CutBaseDate,
                CutBlockDate,
                CutRisesDate,
                CutStringersDate,
                CutTreadDate,
                Location,
                ShipFlag,
                ShipDate
            ) VALUES (
                ${args.NewID},
                ${args.NewOrderNum},
                ${args.REID},
                ${args.ceid},
                ${args.aeid},
                ${args.Delivery},
                ${args.StairType},
                ${args.CutBase},
                ${args.CutBlock},
                ${args.CutRises},
                ${args.CutStringers},
                ${args.CutTread},
                ${args.RDate},
                ${args.CDate},
                ${args.ADate},
                ${args.CutBaseDate},
                ${args.CutBlockDate},
                ${args.CutRisesDate},
                ${args.CutStringersDate},
                ${args.CutTreadDate},
                '${args.Location}',
                ${args.ShipFlag},
                ${args.ShipDate}
        )`,

        'createFullUncomplete': `
            INSERT INTO stairs_server.dbo.Uncomplete (
                WOID,
                WONUM,
                Delivery,
                RComplete,
                reID,
                CComplete,
                ceID,
                AComplete,
                aeID,
                StairType,
                CutBase,
                CutBlock,
                CutRises,
                CutStringers,
                CutTread,
                RDate,
                CDate,
                ADate,
                CutBaseDate,
                CutBlockDate,
                CutRisesDate,
                CutStringersDate,
                CutTreadDate,
                Location,
                ShipFlag,
                ShipDate
            ) VALUES (
                ${args.NewID},
                ${args.NewOrderNum},
                ${args.Delivery},
                ${args.RComplete ? 1 : 0},
                ${args.reID},
                ${args.CComplete ? 1 : 0},
                ${args.ceID},
                ${args.AComplete ? 1 : 0},
                ${args.aeID},
                ${args.StairType},
                ${args.CutBase},
                ${args.CutBlock},
                ${args.CutRises},
                ${args.CutStringers},
                ${args.CutTread},
                ${args.RDate},
                ${args.CDate},
                ${args.ADate},
                ${args.CutBaseDate},
                ${args.CutBlockDate},
                ${args.CutRisesDate},
                ${args.CutStringersDate},
                ${args.CutTreadDate},
                '${args.Location}',
                ${args.ShipFlag},
                ${args.ShipDate}
        )`
    };

    return queries[queryName];
}

module.exports = getQuery;
